#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineScraper.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Wine")]
	public partial class WineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLB_Inventory(LB_Inventory instance);
    partial void UpdateLB_Inventory(LB_Inventory instance);
    partial void DeleteLB_Inventory(LB_Inventory instance);
    partial void InsertWTSO_Rating(WTSO_Rating instance);
    partial void UpdateWTSO_Rating(WTSO_Rating instance);
    partial void DeleteWTSO_Rating(WTSO_Rating instance);
    partial void InsertWTSO_History(WTSO_History instance);
    partial void UpdateWTSO_History(WTSO_History instance);
    partial void DeleteWTSO_History(WTSO_History instance);
    partial void InsertWTSO_Inventory(WTSO_Inventory instance);
    partial void UpdateWTSO_Inventory(WTSO_Inventory instance);
    partial void DeleteWTSO_Inventory(WTSO_Inventory instance);
    #endregion
		
		public WineDataContext() : 
				base(global::WineScraper.Properties.Settings.Default.WineConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LB_Inventory> LB_Inventories
		{
			get
			{
				return this.GetTable<LB_Inventory>();
			}
		}
		
		public System.Data.Linq.Table<WTSO_Rating> WTSO_Ratings
		{
			get
			{
				return this.GetTable<WTSO_Rating>();
			}
		}
		
		public System.Data.Linq.Table<WTSO_History> WTSO_Histories
		{
			get
			{
				return this.GetTable<WTSO_History>();
			}
		}
		
		public System.Data.Linq.Table<WTSO_Inventory> WTSO_Inventories
		{
			get
			{
				return this.GetTable<WTSO_Inventory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LB_Inventory")]
	public partial class LB_Inventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _lbid;
		
		private System.DateTime _CreatedDate;
		
		private string _Title;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<System.DateTime> _Date_last_seen;
		
		private string _Picture_Url;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlbidChanging(string value);
    partial void OnlbidChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnDate_last_seenChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_last_seenChanged();
    partial void OnPicture_UrlChanging(string value);
    partial void OnPicture_UrlChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public LB_Inventory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lbid", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lbid
		{
			get
			{
				return this._lbid;
			}
			set
			{
				if ((this._lbid != value))
				{
					this.OnlbidChanging(value);
					this.SendPropertyChanging();
					this._lbid = value;
					this.SendPropertyChanged("lbid");
					this.OnlbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_last_seen", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_last_seen
		{
			get
			{
				return this._Date_last_seen;
			}
			set
			{
				if ((this._Date_last_seen != value))
				{
					this.OnDate_last_seenChanging(value);
					this.SendPropertyChanging();
					this._Date_last_seen = value;
					this.SendPropertyChanged("Date_last_seen");
					this.OnDate_last_seenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Url", DbType="NVarChar(500)")]
		public string Picture_Url
		{
			get
			{
				return this._Picture_Url;
			}
			set
			{
				if ((this._Picture_Url != value))
				{
					this.OnPicture_UrlChanging(value);
					this.SendPropertyChanging();
					this._Picture_Url = value;
					this.SendPropertyChanged("Picture_Url");
					this.OnPicture_UrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WTSO_Rating")]
	public partial class WTSO_Rating : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _RatingID;
		
		private int _ProductID;
		
		private string _Rating;
		
		private EntityRef<WTSO_Inventory> _WTSO_Inventory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRatingIDChanging(long value);
    partial void OnRatingIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnRatingChanging(string value);
    partial void OnRatingChanged();
    #endregion
		
		public WTSO_Rating()
		{
			this._WTSO_Inventory = default(EntityRef<WTSO_Inventory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RatingID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long RatingID
		{
			get
			{
				return this._RatingID;
			}
			set
			{
				if ((this._RatingID != value))
				{
					this.OnRatingIDChanging(value);
					this.SendPropertyChanging();
					this._RatingID = value;
					this.SendPropertyChanged("RatingID");
					this.OnRatingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._WTSO_Inventory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WTSO_Inventory_WTSO_Rating", Storage="_WTSO_Inventory", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public WTSO_Inventory WTSO_Inventory
		{
			get
			{
				return this._WTSO_Inventory.Entity;
			}
			set
			{
				WTSO_Inventory previousValue = this._WTSO_Inventory.Entity;
				if (((previousValue != value) 
							|| (this._WTSO_Inventory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WTSO_Inventory.Entity = null;
						previousValue.WTSO_Ratings.Remove(this);
					}
					this._WTSO_Inventory.Entity = value;
					if ((value != null))
					{
						value.WTSO_Ratings.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("WTSO_Inventory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WTSO_History")]
	public partial class WTSO_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _HistoryID;
		
		private int _ProductID;
		
		private decimal _Price;
		
		private string _ShippingOffer;
		
		private System.DateTime _OfferDate;
		
		private EntityRef<WTSO_Inventory> _WTSO_Inventory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHistoryIDChanging(long value);
    partial void OnHistoryIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnShippingOfferChanging(string value);
    partial void OnShippingOfferChanged();
    partial void OnOfferDateChanging(System.DateTime value);
    partial void OnOfferDateChanged();
    #endregion
		
		public WTSO_History()
		{
			this._WTSO_Inventory = default(EntityRef<WTSO_Inventory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoryID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long HistoryID
		{
			get
			{
				return this._HistoryID;
			}
			set
			{
				if ((this._HistoryID != value))
				{
					this.OnHistoryIDChanging(value);
					this.SendPropertyChanging();
					this._HistoryID = value;
					this.SendPropertyChanged("HistoryID");
					this.OnHistoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._WTSO_Inventory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingOffer", DbType="NVarChar(500)")]
		public string ShippingOffer
		{
			get
			{
				return this._ShippingOffer;
			}
			set
			{
				if ((this._ShippingOffer != value))
				{
					this.OnShippingOfferChanging(value);
					this.SendPropertyChanging();
					this._ShippingOffer = value;
					this.SendPropertyChanged("ShippingOffer");
					this.OnShippingOfferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfferDate", DbType="DateTime NOT NULL")]
		public System.DateTime OfferDate
		{
			get
			{
				return this._OfferDate;
			}
			set
			{
				if ((this._OfferDate != value))
				{
					this.OnOfferDateChanging(value);
					this.SendPropertyChanging();
					this._OfferDate = value;
					this.SendPropertyChanged("OfferDate");
					this.OnOfferDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WTSO_Inventory_WTSO_History", Storage="_WTSO_Inventory", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public WTSO_Inventory WTSO_Inventory
		{
			get
			{
				return this._WTSO_Inventory.Entity;
			}
			set
			{
				WTSO_Inventory previousValue = this._WTSO_Inventory.Entity;
				if (((previousValue != value) 
							|| (this._WTSO_Inventory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WTSO_Inventory.Entity = null;
						previousValue.WTSO_Histories.Remove(this);
					}
					this._WTSO_Inventory.Entity = value;
					if ((value != null))
					{
						value.WTSO_Histories.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("WTSO_Inventory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WTSO_Inventory")]
	public partial class WTSO_Inventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductID;
		
		private System.DateTime _CreatedDate;
		
		private string _Title;
		
		private string _Picture_Url;
		
		private string _UnitSize;
		
		private string _Varietal;
		
		private System.Nullable<int> _Vintage;
		
		private string _Grape;
		
		private string _Country;
		
		private string _Region;
		
		private string _Appellation;
		
		private string _ABV;
		
		private string _FullDescription;
		
		private System.Nullable<int> _WTSOMemberRating;
		
		private EntitySet<WTSO_Rating> _WTSO_Ratings;
		
		private EntitySet<WTSO_History> _WTSO_Histories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnPicture_UrlChanging(string value);
    partial void OnPicture_UrlChanged();
    partial void OnUnitSizeChanging(string value);
    partial void OnUnitSizeChanged();
    partial void OnVarietalChanging(string value);
    partial void OnVarietalChanged();
    partial void OnVintageChanging(System.Nullable<int> value);
    partial void OnVintageChanged();
    partial void OnGrapeChanging(string value);
    partial void OnGrapeChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnAppellationChanging(string value);
    partial void OnAppellationChanged();
    partial void OnABVChanging(string value);
    partial void OnABVChanged();
    partial void OnFullDescriptionChanging(string value);
    partial void OnFullDescriptionChanged();
    partial void OnWTSOMemberRatingChanging(System.Nullable<int> value);
    partial void OnWTSOMemberRatingChanged();
    #endregion
		
		public WTSO_Inventory()
		{
			this._WTSO_Ratings = new EntitySet<WTSO_Rating>(new Action<WTSO_Rating>(this.attach_WTSO_Ratings), new Action<WTSO_Rating>(this.detach_WTSO_Ratings));
			this._WTSO_Histories = new EntitySet<WTSO_History>(new Action<WTSO_History>(this.attach_WTSO_Histories), new Action<WTSO_History>(this.detach_WTSO_Histories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture_Url", DbType="NVarChar(500)")]
		public string Picture_Url
		{
			get
			{
				return this._Picture_Url;
			}
			set
			{
				if ((this._Picture_Url != value))
				{
					this.OnPicture_UrlChanging(value);
					this.SendPropertyChanging();
					this._Picture_Url = value;
					this.SendPropertyChanged("Picture_Url");
					this.OnPicture_UrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitSize", DbType="NVarChar(100)")]
		public string UnitSize
		{
			get
			{
				return this._UnitSize;
			}
			set
			{
				if ((this._UnitSize != value))
				{
					this.OnUnitSizeChanging(value);
					this.SendPropertyChanging();
					this._UnitSize = value;
					this.SendPropertyChanged("UnitSize");
					this.OnUnitSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varietal", DbType="NVarChar(500)")]
		public string Varietal
		{
			get
			{
				return this._Varietal;
			}
			set
			{
				if ((this._Varietal != value))
				{
					this.OnVarietalChanging(value);
					this.SendPropertyChanging();
					this._Varietal = value;
					this.SendPropertyChanged("Varietal");
					this.OnVarietalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vintage", DbType="Int")]
		public System.Nullable<int> Vintage
		{
			get
			{
				return this._Vintage;
			}
			set
			{
				if ((this._Vintage != value))
				{
					this.OnVintageChanging(value);
					this.SendPropertyChanging();
					this._Vintage = value;
					this.SendPropertyChanged("Vintage");
					this.OnVintageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grape", DbType="NVarChar(500)")]
		public string Grape
		{
			get
			{
				return this._Grape;
			}
			set
			{
				if ((this._Grape != value))
				{
					this.OnGrapeChanging(value);
					this.SendPropertyChanging();
					this._Grape = value;
					this.SendPropertyChanged("Grape");
					this.OnGrapeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(200)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(500)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appellation", DbType="NVarChar(500)")]
		public string Appellation
		{
			get
			{
				return this._Appellation;
			}
			set
			{
				if ((this._Appellation != value))
				{
					this.OnAppellationChanging(value);
					this.SendPropertyChanging();
					this._Appellation = value;
					this.SendPropertyChanged("Appellation");
					this.OnAppellationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABV", DbType="NVarChar(50)")]
		public string ABV
		{
			get
			{
				return this._ABV;
			}
			set
			{
				if ((this._ABV != value))
				{
					this.OnABVChanging(value);
					this.SendPropertyChanging();
					this._ABV = value;
					this.SendPropertyChanged("ABV");
					this.OnABVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullDescription", DbType="NVarChar(MAX)")]
		public string FullDescription
		{
			get
			{
				return this._FullDescription;
			}
			set
			{
				if ((this._FullDescription != value))
				{
					this.OnFullDescriptionChanging(value);
					this.SendPropertyChanging();
					this._FullDescription = value;
					this.SendPropertyChanged("FullDescription");
					this.OnFullDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WTSOMemberRating", DbType="Int")]
		public System.Nullable<int> WTSOMemberRating
		{
			get
			{
				return this._WTSOMemberRating;
			}
			set
			{
				if ((this._WTSOMemberRating != value))
				{
					this.OnWTSOMemberRatingChanging(value);
					this.SendPropertyChanging();
					this._WTSOMemberRating = value;
					this.SendPropertyChanged("WTSOMemberRating");
					this.OnWTSOMemberRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WTSO_Inventory_WTSO_Rating", Storage="_WTSO_Ratings", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<WTSO_Rating> WTSO_Ratings
		{
			get
			{
				return this._WTSO_Ratings;
			}
			set
			{
				this._WTSO_Ratings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WTSO_Inventory_WTSO_History", Storage="_WTSO_Histories", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<WTSO_History> WTSO_Histories
		{
			get
			{
				return this._WTSO_Histories;
			}
			set
			{
				this._WTSO_Histories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_WTSO_Ratings(WTSO_Rating entity)
		{
			this.SendPropertyChanging();
			entity.WTSO_Inventory = this;
		}
		
		private void detach_WTSO_Ratings(WTSO_Rating entity)
		{
			this.SendPropertyChanging();
			entity.WTSO_Inventory = null;
		}
		
		private void attach_WTSO_Histories(WTSO_History entity)
		{
			this.SendPropertyChanging();
			entity.WTSO_Inventory = this;
		}
		
		private void detach_WTSO_Histories(WTSO_History entity)
		{
			this.SendPropertyChanging();
			entity.WTSO_Inventory = null;
		}
	}
}
#pragma warning restore 1591
